/* Versione 4: solo quesiti autonomi. Nessuna variante automatica e nessuna
   spiegazione generata. Ogni record contiene domanda, tre risposte, soluzione,
   spiegazione e fonte. I quiz non sono quesiti ufficiali del concorso. */
window.QUESTIONS=[];
const add=(id,subject,level,question,options,answer,explanation,source='')=>window.QUESTIONS.push({id,subject,level,question,options,answer,explanation,source});
const S={d65:'D.Lgs. 65/2017 — Normattiva',mim:'Linee pedagogiche e Orientamenti nazionali — MIM',gdpr:'Regolamento (UE) 2016/679 — EUR-Lex',garante:'Garante per la protezione dei dati personali',tuel:'D.Lgs. 267/2000 (TUEL) — Normattiva',d165:'D.Lgs. 165/2001 — Normattiva',dpr62:'DPR 62/2013 — Normattiva',agid:'AgID — competenze digitali e servizi digitali'};
// Sistema 0-6 e pedagogia
[
['z1','base','Il Sistema integrato di educazione e di istruzione previsto dal D.Lgs. 65/2017 riguarda:', ['I bambini dalla nascita fino a sei anni','Solo i bambini da tre a sei anni','I minori fino a quattordici anni'],0,'Il Sistema integrato riguarda bambine e bambini dalla nascita fino a sei anni.'],
['z2','base','I nidi e i micronidi accolgono bambini di età compresa tra:', ['Tre e trentasei mesi','Ventiquattro e trentasei mesi','Tre e sei anni'],0,'Nidi e micronidi sono servizi per bambini tra tre e trentasei mesi.'],
['z3','concorso','Le sezioni primavera accolgono bambini di età compresa tra:', ['Ventiquattro e trentasei mesi','Tre e ventiquattro mesi','Tre e sei anni'],0,'Le sezioni primavera accolgono bambini tra ventiquattro e trentasei mesi.'],
['z4','concorso','Secondo il D.Lgs. 65/2017, nidi e micronidi concorrono con le famiglie soprattutto alla:', ['Cura, educazione e socializzazione','Valutazione selettiva del rendimento','Preparazione ai programmi della scuola primaria'],0,'Il decreto attribuisce a nidi e micronidi funzioni di cura, educazione e socializzazione, svolte in concorso con le famiglie.'],
['z5','base','Nel Sistema integrato, la scuola dell’infanzia accoglie bambini:', ['Dai tre ai sei anni','Dalla nascita ai tre anni','Dai sei agli undici anni'],0,'La scuola dell’infanzia accoglie bambini dai tre ai sei anni e opera in continuità con i servizi educativi e il primo ciclo.'],
['z6','difficile','Quale descrizione è corretta per i Poli per l’infanzia?', ['Riuniscono più strutture 0-6 in un percorso educativo unitario','Sono esclusivamente uffici comunali','Accolgono solo bambini tra ventiquattro e trentasei mesi'],0,'I Poli possono riunire più strutture in un unico plesso o in edifici vicini, favorendo un percorso educativo unitario.'],
['z7','concorso','Un obiettivo strategico del Sistema integrato è:', ['Ampliare l’accessibilità dei servizi e riequilibrare l’offerta sul territorio','Ridurre progressivamente i servizi educativi','Limitare i servizi ai soli capoluoghi'],0,'Il D.Lgs. 65/2017 richiama ampliamento, accessibilità e riequilibrio territoriale.'],
['z8','base','Le Linee pedagogiche per il sistema integrato zero-sei sono richiamate nel bando attraverso:', ['DM 34/2021','DM 43/2022','DPR 62/2013'],0,'Nel bando il riferimento indicato per le Linee pedagogiche è il DM 34/2021.'],
['z9','base','Gli Orientamenti nazionali per i servizi educativi per l’infanzia sono richiamati nel bando attraverso:', ['DM 43/2022','DM 34/2021','D.Lgs. 165/2001'],0,'Nel bando il riferimento indicato per gli Orientamenti nazionali è il DM 43/2022.'],
['z10','concorso','La documentazione educativa serve principalmente a:', ['Rendere visibili e condivisibili i percorsi educativi','Sostituire l’osservazione dei bambini','Valutare esclusivamente le famiglie'],0,'La documentazione dà evidenza ai percorsi, sostiene la riflessione professionale e la condivisione con bambini, gruppo di lavoro e famiglie.'],
['z11','concorso','Se l’osservazione mostra che un’attività coinvolge poco alcuni bambini, la scelta educativa più coerente è:', ['Rivedere la proposta e adattarla alle osservazioni','Riproporla identica senza verifica','Escludere i bambini meno coinvolti'],0,'L’osservazione orienta la progettazione: una proposta può essere verificata e riorientata.'],
['z12','difficile','Quale comportamento esprime corresponsabilità educativa con le famiglie?', ['Condividere osservazioni e costruire un dialogo sul percorso educativo','Informare la famiglia solo in caso di emergenza','Delegare alla famiglia tutte le scelte del servizio'],0,'La corresponsabilità richiede ascolto, comunicazione e riconoscimento reciproco dei ruoli educativi.'],
['z13','base','Nel nido, l’organizzazione di spazi, tempi e materiali:', ['È parte del progetto educativo','Ha soltanto una funzione estetica','È estranea all’esperienza dei bambini'],0,'Spazi, tempi e materiali influenzano relazioni, autonomie, gioco ed esperienze dei bambini.'],
['z14','concorso','Una progettazione educativa di qualità dovrebbe essere:', ['Flessibile, osservabile e verificabile','Rigida e identica in ogni contesto','Indipendente dai bisogni del gruppo'],0,'La progettazione parte dall’osservazione e può essere aggiornata sulla base delle esperienze reali.'],
['z15','difficile','In un gruppo con diversi tempi di partecipazione, l’educatore dovrebbe:', ['Predisporre modalità di partecipazione flessibili e inclusive','Chiedere a tutti la stessa prestazione nello stesso momento','Concentrare l’attività solo sui bambini più rapidi'],0,'Un contesto inclusivo riconosce differenze di tempi, stili e bisogni, favorendo la partecipazione di tutti.'],
['z16','base','La valutazione dei percorsi educativi serve anche a:', ['Riflettere sull’efficacia delle proposte e orientare il progetto','Classificare i bambini in base al rendimento','Eliminare l’osservazione'],0,'La valutazione è uno strumento professionale di riflessione e miglioramento della progettazione.'],
['z17','concorso','Il gioco nella prima infanzia è soprattutto:', ['Un contesto di esperienza, relazione e apprendimento','Un’attività estranea al progetto educativo','Un premio da concedere solo dopo le attività'],0,'Il gioco è una modalità fondamentale con cui il bambino esplora, comunica, costruisce significati e relazioni.'],
['z18','concorso','Le routine quotidiane al nido:', ['Possono avere valore educativo e relazionale','Sono semplici pause senza significato educativo','Devono essere gestite senza attenzione ai bambini'],0,'Cura, pasti, sonno e cambi sono occasioni di relazione, autonomia e costruzione di sicurezza.'],
['z19','difficile','Di fronte a un conflitto tra due bambini, una risposta educativa adeguata è:', ['Accompagnare la situazione, nominare ciò che accade e sostenere soluzioni possibili','Ignorare sempre il conflitto','Punire automaticamente entrambi senza ascolto'],0,'L’adulto può mediare e sostenere la regolazione emotiva, senza negare il conflitto né applicare risposte automatiche.'],
['z20','base','Lo sviluppo nella prima infanzia comprende:', ['Dimensioni emotive, affettive, cognitive, sociali e motorie','Solo la dimensione cognitiva','Solo la dimensione motoria'],0,'Lo sviluppo è globale: le sue dimensioni sono interconnesse e vanno considerate insieme.']
].forEach(x=>add(x[0],'Normativa 0-6',x[1],x[2],x[3],x[4],x[5],x[0].startsWith('z')&&+x[0].slice(1)<=7?'d65':x[0]==='z8'||x[0]==='z9'?'mim':'mim'));
// Privacy
[
['p1','base','Il GDPR è:', ['Il Regolamento (UE) 2016/679','Il D.Lgs. 165/2001','Il D.Lgs. 267/2000'],0,'Il GDPR è il Regolamento (UE) 2016/679 relativo alla protezione delle persone fisiche con riguardo al trattamento dei dati personali.'],
['p2','base','Il principio di minimizzazione richiede che i dati siano:', ['Adeguati, pertinenti e limitati a quanto necessario','Raccolti nella quantità più ampia possibile','Conservati senza limiti di tempo'],0,'Si raccolgono solo i dati realmente necessari rispetto alle finalità del trattamento.'],
['p3','concorso','Il principio di limitazione della finalità richiede che i dati siano raccolti:', ['Per finalità determinate, esplicite e legittime','Per qualunque uso futuro non definito','Senza indicare perché servono'],0,'Le finalità devono essere definite e legittime; non è lecito riutilizzare i dati in modo incompatibile con esse.'],
['p4','base','Il diritto di accesso consente all’interessato di:', ['Ottenere informazioni sui propri dati e sul loro trattamento','Accedere ai dati di qualsiasi altra persona','Modificare direttamente gli archivi del titolare'],0,'L’accesso riguarda i dati personali dell’interessato e le informazioni previste dal GDPR sul trattamento.'],
['p5','concorso','Il titolare del trattamento è:', ['Chi determina finalità e mezzi del trattamento','Chiunque riceva una comunicazione','Solo il Garante della privacy'],0,'Il titolare decide perché e come i dati personali vengono trattati.'],
['p6','concorso','Il trattamento di dati personali comprende:', ['Qualsiasi operazione sui dati, come raccolta, consultazione o cancellazione','Solo la raccolta dei dati','Solo la cancellazione dei dati'],0,'Il GDPR definisce trattamento in modo ampio: comprende ogni operazione o insieme di operazioni sui dati.'],
['p7','concorso','Il principio di esattezza richiede che i dati siano:', ['Esatti e, se necessario, aggiornati','Sempre pubblici','Conservati anche se inesatti'],0,'Occorre adottare misure ragionevoli affinché dati inesatti siano rettificati o cancellati senza ritardo.'],
['p8','difficile','Il principio di integrità e riservatezza richiede:', ['Misure adeguate contro accessi non autorizzati, perdita o distruzione','La diffusione dei dati al maggior numero di persone','L’assenza di misure di sicurezza'],0,'I dati devono essere trattati con una sicurezza adeguata, anche attraverso misure tecniche e organizzative.'],
['p9','difficile','L’accountability comporta che il titolare:', ['Sia responsabile del rispetto dei principi e possa dimostrarlo','Trasferisca ogni responsabilità all’interessato','Non debba documentare le proprie scelte'],0,'Il titolare non deve solo rispettare i principi: deve anche essere in grado di comprovare di averlo fatto.'],
['p10','concorso','Quale può essere una base giuridica del trattamento?', ['L’adempimento di un obbligo legale del titolare','La semplice curiosità di chi tratta i dati','L’assenza di qualunque finalità'],0,'L’art. 6 GDPR elenca le basi giuridiche, tra cui l’adempimento di un obbligo legale.'],
['p11','difficile','I dati relativi alla salute sono:', ['Categorie particolari di dati personali','Dati anonimi per definizione','Dati liberamente pubblicabili'],0,'Il GDPR include i dati relativi alla salute tra le categorie particolari, soggette a protezioni specifiche.'],
['p12','concorso','Il diritto di rettifica permette di:', ['Ottenere la correzione di dati personali inesatti','Cancellare dati di altre persone','Cambiare le finalità del titolare'],0,'L’interessato può chiedere la rettifica dei propri dati inesatti e l’integrazione di quelli incompleti.'],
['p13','concorso','Il diritto alla cancellazione è noto anche come:', ['Diritto all’oblio','Diritto di accesso','Diritto di opposizione'],0,'Il GDPR disciplina il diritto alla cancellazione all’art. 17, spesso chiamato diritto all’oblio.'],
['p14','difficile','Una violazione dei dati personali può includere:', ['La divulgazione non autorizzata di dati','Un semplice errore di battitura in un testo generico','L’apertura ordinaria di un documento autorizzato'],0,'Un data breach comprende, tra l’altro, distruzione, perdita, modifica, divulgazione non autorizzata o accesso non autorizzato a dati personali.'],
['p15','difficile','Inviare foto identificabili di bambini a una chat personale non collegata al servizio è:', ['Incompatibile con finalità e riservatezza del trattamento','Sempre lecito se le foto sono gradevoli','Irrilevante per la protezione dei dati'],0,'L’uso di immagini identificabili deve essere coerente con la finalità del servizio e protetto da divulgazioni non autorizzate.'],
['p16','base','Nel programma del concorso, la privacy comprende:', ['GDPR e D.Lgs. 196/2003','Solo il GDPR','Solo il D.Lgs. 165/2001'],0,'Il bando richiama il GDPR e il Codice in materia di protezione dei dati personali, D.Lgs. 196/2003.']
].forEach(x=>add(x[0],'Privacy',x[1],x[2],x[3],x[4],x[5],x[0]==='p4'?'garante':'gdpr'));
// TUEL e pubblico impiego
[
['t1','base','Il Comune è:', ['Un ente locale territoriale','Un organo giudiziario','Un ministero'],0,'Il Comune è un ente locale territoriale disciplinato dal TUEL.'],
['t2','base','Quali sono gli organi di governo del Comune?', ['Sindaco, Giunta e Consiglio','Sindaco, Prefetto e Questore','Consiglio, Regione e Prefetto'],0,'Il TUEL individua Consiglio, Giunta e Sindaco come organi di governo del Comune.'],
['t3','concorso','Il Consiglio comunale esercita principalmente funzioni:', ['Di indirizzo e controllo politico-amministrativo','Solo esecutive','Giudiziarie'],0,'Il Consiglio è l’organo di indirizzo e di controllo politico-amministrativo.'],
['t4','concorso','La Giunta comunale:', ['Collabora con il sindaco nel governo del Comune','Sostituisce il Consiglio in ogni competenza','È un organo giudiziario'],0,'La Giunta collabora con il sindaco e opera mediante deliberazioni collegiali.'],
['t5','difficile','La Giunta compie gli atti di governo che:', ['Non siano riservati dalla legge al Consiglio e non ricadano nelle competenze di altri organi','Siano sempre riservati al Consiglio','Siano esclusivamente atti giudiziari'],0,'Il TUEL definisce così la competenza generale della Giunta nell’ambito delle funzioni di governo.'],
['t6','concorso','Il sindaco, tra l’altro:', ['Rappresenta l’ente e sovrintende al funzionamento di servizi e uffici','Svolge solo funzioni giudiziarie','È nominato dal Consiglio regionale'],0,'Il sindaco rappresenta l’ente, convoca e presiede la Giunta e sovrintende a servizi, uffici ed esecuzione degli atti.'],
['t7','base','Il D.Lgs. 165/2001 disciplina principalmente:', ['Il lavoro alle dipendenze delle pubbliche amministrazioni','Il sistema integrato zero-sei','Il diritto di famiglia'],0,'Il decreto reca norme generali sull’ordinamento del lavoro alle dipendenze delle amministrazioni pubbliche.'],
['t8','base','Il Codice di comportamento dei dipendenti pubblici è disciplinato principalmente dal:', ['DPR 62/2013','DPR 487/1994','D.Lgs. 267/2000'],0,'Il DPR 62/2013 contiene il Codice di comportamento dei dipendenti pubblici.'],
['t9','concorso','Il dipendente pubblico deve perseguire:', ['L’interesse pubblico nel rispetto della legge','Il proprio interesse personale','L’interesse del soggetto più insistente'],0,'Il dipendente svolge i compiti nel rispetto della legge, perseguendo l’interesse pubblico senza abusare della posizione o dei poteri.'],
['t10','concorso','In caso di conflitto di interessi, il dipendente pubblico deve:', ['Astenersi','Proseguire senza comunicarlo','Accettare vantaggi se di modico valore'],0,'Il Codice richiede indipendenza e imparzialità e impone l’astensione in caso di conflitto di interessi.'],
['t11','concorso','Le informazioni conosciute per ragioni di ufficio:', ['Non devono essere usate a fini privati','Possono essere condivise liberamente con amici','Possono servire a favorire conoscenti'],0,'Il dipendente non usa a fini privati le informazioni di cui dispone per ragioni di ufficio.'],
['t12','difficile','La gestione delle risorse pubbliche deve seguire una logica di:', ['Contenimento dei costi senza pregiudicare la qualità dei risultati','Massima spesa senza valutazione','Riduzione della qualità per principio'],0,'Il Codice richiama economicità, efficienza ed efficacia, con contenimento dei costi senza danno per la qualità.'],
['t13','concorso','Nei rapporti con i destinatari dell’azione amministrativa, il dipendente assicura:', ['Parità di trattamento a parità di condizioni','Preferenza per conoscenti e amici','Trattamenti diversi senza ragione'],0,'Il Codice vieta azioni arbitrarie e discriminazioni e richiede parità di trattamento a parità di condizioni.'],
['t14','difficile','Un dipendente può chiedere un regalo come corrispettivo per un atto d’ufficio?', ['No, neppure se di modico valore','Sì, se il regalo è di modico valore','Sì, se lo chiede una persona conosciuta'],0,'Il Codice vieta di chiedere regali o altre utilità quale corrispettivo per compiere un atto d’ufficio.']
].forEach(x=>add(x[0],'TUEL e PA',x[1],x[2],x[3],x[4],x[5],x[0].startsWith('t')&&+x[0].slice(1)>=8?'dpr62':x[0]==='t7'?'d165':'tuel'));
// Inglese B2
[
['en1','base','Choose the correct sentence.', ['If I had more time, I would study more.','If I would have more time, I will study more.','If I have more time, I would study more.'],0,'Second conditional: If + past simple, would + base form.'],
['en2','concorso','By the time the educator arrived, the children ____ their lunch.', ['had finished','have finish','were finish'],0,'Past perfect: had + past participle, per un’azione conclusa prima di un’altra azione nel passato.'],
['en3','base','Choose the correct sentence.', ['The documents must be signed before Friday.','The documents must signed before Friday.','The documents must be signing before Friday.'],0,'Con un verbo modale al passivo si usa: modal + be + past participle.'],
['en4','concorso','She said that she ____ the report the following day.', ['would send','will sent','has send'],0,'Nel reported speech, will diventa normalmente would.'],
['en5','base','Choose the correct sentence.', ['I have been working here for three years.','I have worked here since three years.','I am working here since three years.'],0,'For introduce una durata; il present perfect continuous è corretto in questa frase.'],
['en6','concorso','If the child ____ tired, we would stop the activity.', ['were','would be','had been'],0,'Second conditional: If + past simple, would + verbo. Con be, were è la forma tradizionale anche con soggetto singolare.'],
['en7','base','Choose the correct sentence.', ['The parents were informed about the meeting.','The parents were inform about the meeting.','The parents have informed yesterday about the meeting.'],0,'Past simple passive: were + past participle.'],
['en8','concorso','The educator is responsible ____ documenting the children’s activities.', ['for','of','to'],0,'L’espressione corretta è responsible for + -ing.'],
['en9','concorso','Choose the correct sentence.', ['Although he was tired, he continued working.','Although he was tired, but he continued working.','Despite he was tired, he continued working.'],0,'Although non è seguito da but. Despite richiede un nome o una forma in -ing, non una frase completa.'],
['en10','difficile','The report ____ before the meeting started.', ['had been completed','has been complete','was completing'],0,'Past perfect passive: had been + past participle.'],
['en11','concorso','The educator ____ works here speaks English.', ['who','which','where'],0,'Who è il pronome relativo usato per le persone.'],
['en12','base','You ____ share children’s personal data without authorisation.', ['must not','do not have','should to not'],0,'Must not esprime un divieto.'],
['en13','difficile','If they had informed us earlier, we ____ the plan.', ['would have changed','would change','had changed'],0,'Third conditional: If + past perfect, would have + past participle.'],
['en14','concorso','Choose the correct sentence.', ['Despite being tired, she attended the meeting.','Despite she was tired, she attended the meeting.','Despite of being tired, she attended the meeting.'],0,'Despite è seguito da nome o forma in -ing. Non si usa despite of.'],
['en15','base','She has worked in the nursery ____ 2023.', ['since','for','during'],0,'Since introduce il momento iniziale di un periodo che arriva fino al presente.'],
['en16','base','They have worked together ____ four years.', ['for','since','from'],0,'For introduce una durata.'],
['en17','concorso','I look forward to ____ from you.', ['hearing','hear','heard'],0,'Look forward to è seguito da verbo in -ing.'],
['en18','difficile','Neither the parents nor the child ____ late.', ['was','were','are'],0,'Con neither…nor il verbo concorda con il soggetto più vicino: child è singolare.'],
['en19','concorso','The activity ____ by the team last week.', ['was planned','was plan','has planning'],0,'Past simple passive: was/were + past participle.'],
['en20','base','You should ____ the instructions carefully.', ['read','to read','reading'],0,'Dopo should si usa la forma base del verbo.']
].forEach(x=>add(x[0],'Inglese B2',x[1],x[2],x[3],x[4],x[5]));
// Informatica
[
['i1','base','Quale tra questi è un browser web?', ['Google Chrome','Microsoft Excel','Windows'],0,'Google Chrome è un browser per navigare sul web. Excel è un foglio di calcolo e Windows è un sistema operativo.'],
['i2','base','Quale tra questi è un sistema operativo?', ['Windows','Microsoft Word','Google Chrome'],0,'Windows è un sistema operativo; Word è un programma di videoscrittura e Chrome è un browser.'],
['i3','base','Quale estensione identifica normalmente un documento Microsoft Word?', ['.docx','.xlsx','.pptx'],0,'.docx è l’estensione tipica di un documento Word; .xlsx è Excel e .pptx è PowerPoint.'],
['i4','base','Quale estensione identifica normalmente un foglio di calcolo Microsoft Excel?', ['.xlsx','.docx','.pptx'],0,'.xlsx è l’estensione tipica di un foglio di calcolo Excel.'],
['i5','base','Il phishing è:', ['Una tecnica fraudolenta per ottenere dati tramite comunicazioni ingannevoli','Un programma per creare presentazioni','Un sistema operativo'],0,'Il phishing usa messaggi, email o siti falsi per indurre una persona a comunicare credenziali o altri dati.'],
['i6','concorso','Davanti a un’email inattesa che chiede credenziali di accesso, è più prudente:', ['Verificare il mittente e non inserire dati tramite link sospetti','Inviare subito le credenziali','Inoltrare l’email a tutti i contatti'],0,'È buona pratica controllare la provenienza del messaggio e non usare link sospetti per inserire credenziali.'],
['i7','concorso','Un backup è:', ['Una copia di sicurezza dei dati','La cancellazione definitiva dei dati','Un tipo di virus'],0,'Il backup consente di recuperare dati in caso di perdita, errore o guasto.'],
['i8','concorso','SPID permette:', ['L’accesso con un’unica identità digitale ai servizi online di PA e soggetti aderenti','Di creare file Word','Di eliminare virus dal computer'],0,'SPID è il Sistema Pubblico di Identità Digitale per l’accesso ai servizi online della PA e dei soggetti privati aderenti.'],
['i9','difficile','Il secondo livello SPID prevede normalmente:', ['Credenziali più un codice temporaneo OTP o un’app su dispositivo','Solo un documento cartaceo','Nessuna credenziale'],0,'Il secondo livello aggiunge un fattore di sicurezza, come OTP o app, alle credenziali.'],
['i10','concorso','La PEC:', ['Ha valore legale analogo a una raccomandata con avviso di ricevimento','È un social network','È un programma antivirus'],0,'La posta elettronica certificata attesta l’invio e la consegna del messaggio secondo le regole del servizio.'],
['i11','difficile','Quale comportamento migliora la sicurezza di un dispositivo?', ['Aggiornare regolarmente sistema operativo e programmi','Ignorare gli avvisi di sicurezza','Usare la stessa password semplice ovunque'],0,'Gli aggiornamenti correggono vulnerabilità note; password robuste e differenti riducono il rischio di accessi indebiti.'],
['i12','concorso','Prima di aprire un allegato inatteso è opportuno:', ['Verificare mittente e affidabilità del messaggio','Aprirlo sempre subito','Inoltrarlo a tutti per chiedere un parere'],0,'Allegati inattesi possono contenere contenuti dannosi: prima va verificata la provenienza.']
].forEach(x=>add(x[0],'Informatica',x[1],x[2],x[3],x[4],x[5],'agid'));

// Livello difficile: quesiti distinti, con dettagli normativi o distrattori vicini.
[
['zd1','Normativa 0-6','Secondo il D.Lgs. 65/2017, la scuola dell’infanzia opera in continuità:', ['Con i servizi educativi per l’infanzia e con il primo ciclo di istruzione','Solo con la scuola secondaria di primo grado','Esclusivamente con i servizi sanitari'],0,'La scuola dell’infanzia ha una funzione strategica nel Sistema integrato e opera in continuità sia con i servizi educativi sia con il primo ciclo di istruzione.','d65'],
['zd2','Normativa 0-6','Quale affermazione sulle sezioni primavera è corretta?', ['Possono essere gestite anche dallo Stato','Devono essere gestite esclusivamente da soggetti privati','Possono accogliere bambini fino a sei anni'],0,'Le sezioni primavera, a differenza degli altri servizi educativi indicati nel comma, possono essere gestite anche dallo Stato.','d65'],
['zd3','Normativa 0-6','Nei Poli per l’infanzia, la condivisione di servizi generali, spazi collettivi e risorse professionali serve anche a:', ['Favorire flessibilità e diversificazione nell’uso delle risorse','Eliminare ogni differenza tra nido e scuola dell’infanzia','Sostituire la progettazione educativa con la sola gestione logistica'],0,'Il D.Lgs. 65/2017 collega la condivisione delle risorse alla massima flessibilità e diversificazione nel loro utilizzo.','d65'],
['zd4','Normativa 0-6','Quale scelta esprime meglio la differenza tra osservazione e valutazione educativa?', ['L’osservazione raccoglie elementi sui processi; la valutazione li utilizza per riflettere e orientare il progetto','L’osservazione classifica i bambini e la valutazione registra solo presenze','Non esiste alcuna differenza tra osservazione e valutazione'],0,'L’osservazione alimenta la comprensione dei processi; la valutazione professionale usa questi elementi per verificare e riorientare le proposte.','mim'],
['zd5','Normativa 0-6','In una documentazione educativa rispettosa della privacy, è più corretto:', ['Selezionare dati e immagini necessari alla finalità educativa e condividerli solo nei canali previsti','Inserire sempre tutti i dati disponibili per rendere il documento più completo','Usare immagini identificabili in gruppi personali per velocizzare la condivisione'],0,'Documentazione educativa e protezione dei dati richiedono finalità chiare, minimizzazione e canali di condivisione appropriati.','mim'],
['pd1','Privacy','Quale situazione descrive meglio il principio di limitazione della conservazione?', ['Un servizio definisce tempi di conservazione coerenti con la finalità e verifica periodicamente i dati non più necessari','Un servizio conserva ogni dato perché potrebbe essere utile in futuro','Un servizio cancella tutti i dati il giorno dopo la raccolta, senza considerare obblighi di legge'],0,'I dati vanno conservati per un periodo non superiore al necessario per le finalità; non è né conservazione indefinita né cancellazione indiscriminata.','gdpr'],
['pd2','Privacy','Quale affermazione distingue correttamente titolare e responsabile del trattamento?', ['Il titolare decide finalità e mezzi; il responsabile tratta dati per conto del titolare','Il responsabile è sempre la persona cui si riferiscono i dati','Titolare e responsabile sono sempre la stessa figura per definizione'],0,'Il titolare determina finalità e mezzi; il responsabile tratta dati personali per conto del titolare, secondo le istruzioni ricevute.','gdpr'],
['pd3','Privacy','Quale condotta è più coerente con il principio di minimizzazione quando si prepara un elenco per un’attività?', ['Inserire solo le informazioni necessarie allo svolgimento dell’attività','Inserire anche informazioni sanitarie non pertinenti “per sicurezza”','Inserire contatti personali di familiari non coinvolti'],0,'La minimizzazione richiede dati adeguati, pertinenti e limitati a quanto necessario rispetto alla finalità.','gdpr'],
['pd4','Privacy','Se una richiesta di accesso ai dati personali è complessa, il titolare:', ['Può estendere il termine nei casi previsti, ma deve informare l’interessato entro un mese dalla richiesta','Può non rispondere finché la richiesta non viene ripetuta','Deve comunicare automaticamente i dati di altre persone'],0,'Il GDPR consente, nei casi previsti, la proroga del termine; l’interessato deve comunque ricevere informazione entro un mese.','garante'],
['pd5','Privacy','Quale caso richiede particolare attenzione perché riguarda categorie particolari di dati?', ['Un documento che contiene informazioni sulla salute di un bambino','Un elenco dei titoli di libri presenti in una biblioteca','Il numero complessivo di utenti di un servizio, senza identificativi'],0,'I dati sulla salute sono categorie particolari di dati personali e richiedono tutele specifiche.','gdpr'],
['td1','TUEL e PA','Quale tra i seguenti atti rientra nella competenza fondamentale del Consiglio comunale?', ['L’approvazione di statuti, regolamenti e bilanci nei casi previsti dal TUEL','La gestione quotidiana di ogni singola attività d’ufficio','L’adozione di sentenze nei contenziosi'],0,'L’art. 42 TUEL attribuisce al Consiglio gli atti fondamentali, tra cui statuti, regolamenti e strumenti di programmazione e bilancio indicati dalla legge.','tuel'],
['td2','TUEL e PA','Il Sindaco convoca e presiede il Consiglio comunale:', ['Quando non è previsto il presidente del Consiglio','In ogni Comune, anche quando il presidente del Consiglio è previsto','Mai, perché può presiedere solo la Giunta'],0,'L’art. 50 TUEL precisa che il Sindaco convoca e presiede il Consiglio quando non è previsto il presidente del Consiglio.','tuel'],
['td3','TUEL e PA','Quale comportamento è conforme al Codice di comportamento nei rapporti con i cittadini?', ['Evitare azioni arbitrarie e discriminazioni, assicurando parità di trattamento a parità di condizioni','Favorire chi conosce personalmente l’ufficio','Rifiutare senza motivazione ogni richiesta complessa'],0,'Il DPR 62/2013 richiede parità di trattamento e vieta azioni arbitrarie o discriminatorie.','dpr62'],
['td4','TUEL e PA','Un dipendente riceve da un soggetto interessato a una pratica un regalo in cambio di un atto d’ufficio. Qual è la condotta corretta?', ['Non accettare il regalo, perché è collegato all’esercizio delle funzioni','Accettarlo se dichiara di non essere influenzato','Accettarlo se il valore è basso'],0,'Il Codice vieta di chiedere o accettare regali o utilità come corrispettivo per atti d’ufficio.','dpr62'],
['end1','Inglese B2','Choose the correct option: “Had the educator ____ earlier, the problem could have been avoided.”', ['been informed','informed','being informed'],0,'In an inverted third conditional, “Had + subject + past participle” replaces “If the educator had been informed…”.'],
['end2','Inglese B2','Choose the correct option: “No sooner ____ the meeting started than the fire alarm rang.”', ['had','has','did'],0,'The formal structure is “No sooner had + subject + past participle … than …”.'],
['end3','Inglese B2','Choose the correct option: “The coordinator suggested that the team ____ the procedure.”', ['review','reviews','reviewed'],0,'After suggest that, formal English can use the subjunctive base form: that the team review.'],
['end4','Inglese B2','Choose the correct option: “The children were so engaged ____ they did not notice the time.”', ['that','than','as'],0,'The structure is so + adjective + that + clause.'],
['end5','Inglese B2','Choose the correct option: “Not only ____ the activity inclusive, but it was also engaging.”', ['was','it was','has been'],0,'After a negative or limiting adverbial at the beginning, formal English uses inversion: Not only was…'],
['id1','Informatica','Quale comportamento riduce maggiormente il rischio di phishing?', ['Verificare dominio, mittente e collegamento prima di inserire credenziali','Usare il link ricevuto se il messaggio sembra urgente','Condividere la password con un collega per controllare il messaggio'],0,'I messaggi di phishing sfruttano urgenza e imitazione. Occorre verificare indipendentemente sito e mittente e non condividere credenziali.','agid'],
['id2','Informatica','Quale affermazione sulla PEC è corretta?', ['Certifica invio e consegna del messaggio, ma non garantisce da sola l’identità materiale di chi lo ha scritto','È identica a un normale social network','Sostituisce sempre l’autenticazione con SPID'],0,'La PEC offre valore legale nella trasmissione; non equivale, da sola, alla garanzia dell’identità materiale dell’autore del messaggio.','agid'],
['id3','Informatica','Qual è la soluzione più sicura per gestire password di servizi diversi?', ['Usare password robuste e differenti, preferibilmente conservate con strumenti affidabili','Usare la stessa password semplice per tutti i servizi','Salvare tutte le password in una chat di gruppo'],0,'Password riutilizzate aumentano il danno di una compromissione. Password robuste e differenti riducono il rischio.','agid']
].forEach(x=>add(x[0],x[1],'difficile',x[2],x[3],x[4],x[5],x[6]));

/* Le precedenti domande "difficile" erano buone domande da concorso, ma non
   abbastanza selettive. Restano disponibili nel livello Concorso. */
const demotedDifficult=new Set(['z6','z15','z19','p8','p9','p11','p14','p15','t5','t12','t14','en10','en13','en14','en18','i9','i11']);
window.QUESTIONS.forEach(q=>{if(demotedDifficult.has(q.id))q.level='concorso'});

/* Livello difficile: confronto tra disposizioni, eccezioni e casi applicativi.
   Ogni quesito è autonomo: non sono varianti della stessa domanda. */
[
['hdz1','Normativa 0-6','Nel D.Lgs. 65/2017, quale abbinamento tra servizio e fascia d’età è corretto?', ['Nidi/micronidi: 3-36 mesi; sezioni primavera: 24-36 mesi','Nidi/micronidi: 24-36 mesi; sezioni primavera: 3-36 mesi','Nidi/micronidi: 0-6 anni; sezioni primavera: 3-6 anni'],0,'Il D.Lgs. 65/2017 distingue chiaramente le fasce: nidi e micronidi da 3 a 36 mesi; sezioni primavera da 24 a 36 mesi. Le fasce possono sovrapporsi, ma le funzioni dei servizi non coincidono.','d65'],
['hdz2','Normativa 0-6','Quale affermazione distingue correttamente il nido dalla sezione primavera?', ['Il nido assicura pasto e riposo; la sezione primavera favorisce in particolare la continuità del percorso 0-6','La sezione primavera accoglie bambini fino a sei anni, mentre il nido solo fino a ventiquattro mesi','Il nido è gestito solo dallo Stato, mentre la sezione primavera solo dai privati'],0,'Il D.Lgs. attribuisce a nidi e micronidi anche pasto e riposo, mentre lega le sezioni primavera alla continuità zero-sei. Le altre affermazioni alterano fasce d’età e modalità di gestione.','d65'],
['hdz3','Normativa 0-6','Un Comune istituisce un Polo per l’infanzia con nido e scuola dell’infanzia in edifici adiacenti. Quale elemento è essenziale perché sia coerente con il D.Lgs. 65/2017?', ['Un percorso educativo unitario che rispetti età, tempi e stili di apprendimento','L’unificazione di tutte le attività senza distinzione per età','La sola condivisione dell’edificio, senza progettazione comune'],0,'Il Polo non è una semplice vicinanza logistica: il decreto richiede un percorso educativo unitario, nel rispetto dell’età e dei tempi e stili di apprendimento di ciascuno.','d65'],
['hdz4','Normativa 0-6','Quale scelta è più coerente con il ruolo della scuola dell’infanzia nel Sistema integrato?', ['Progettare continuità sia con i servizi educativi sia con il primo ciclo di istruzione','Operare solo come fase conclusiva senza raccordo con altri servizi','Assorbire integralmente le funzioni dei nidi'],0,'Il D.Lgs. 65/2017 attribuisce alla scuola dell’infanzia una funzione strategica e la colloca in continuità sia a valle sia a monte del percorso educativo.','d65'],
['hdz5','Normativa 0-6','In una riunione, il gruppo sostiene che “inclusione” significhi proporre la medesima attività, con gli stessi tempi, a tutti i bambini. Qual è la correzione più adeguata?', ['L’inclusione richiede accessibilità e partecipazione, anche adattando tempi, materiali e modalità','L’inclusione consiste nell’evitare qualsiasi proposta comune','L’inclusione riguarda solo bambini con certificazione'],0,'L’inclusione non è uniformità. Richiede di progettare contesti nei quali ciascun bambino possa partecipare, valorizzando differenze e bisogni.','mim'],
['hdz6','Normativa 0-6','Quale uso della documentazione è pedagogicamente più corretto?', ['Raccogliere tracce per riflettere sul processo, condividerlo e riorientare la progettazione','Usarla per attribuire etichette stabili ai bambini','Ridurre l’esperienza educativa a fotografie senza contesto'],0,'La documentazione non è un archivio neutro né uno strumento di classificazione: rende leggibili processi e scelte, sostenendo riflessione e condivisione.','mim'],
['hdz7','Normativa 0-6','Un educatore nota che un bambino osserva a lungo prima di partecipare al gioco. Quale interpretazione è più professionale?', ['Registrare l’osservazione, confrontarla nel tempo e progettare occasioni di partecipazione non forzate','Concludere subito che il bambino non è interessato al gruppo','Obbligarlo a partecipare per eliminare il comportamento'],0,'L’osservazione educativa è continuativa e contestualizzata. Evita etichette immediate e sostiene interventi rispettosi dei tempi del bambino.','mim'],
['hdp1','Privacy','Una coordinatrice prepara un registro per le uscite e inserisce nome del bambino, contatto del genitore, allergie, situazione lavorativa dei genitori e una nota clinica non collegata all’uscita. Quale principio è maggiormente violato?', ['Minimizzazione dei dati','Esattezza dei dati','Portabilità dei dati'],0,'Per una specifica uscita si raccolgono solo dati adeguati e pertinenti alla sua organizzazione e sicurezza. Dati lavorativi o clinici non necessari sono eccedenti.','gdpr'],
['hdp2','Privacy','Quale affermazione descrive correttamente il rapporto tra consenso e altre basi giuridiche?', ['Il consenso è una possibile base giuridica, ma non è l’unica prevista dal GDPR','Ogni trattamento della PA richiede sempre e soltanto consenso','Se c’è consenso, non è più necessario rispettare minimizzazione e finalità'],0,'Il GDPR prevede diverse basi giuridiche. Qualunque sia la base, restano applicabili i principi dell’art. 5, compresi finalità e minimizzazione.','gdpr'],
['hdp3','Privacy','Una famiglia chiede l’accesso ai dati del proprio figlio conservati dal servizio. Il servizio può limitarsi a indicare genericamente le categorie di dati trattati?', ['No: deve fornire le informazioni e l’accesso previsti dall’art. 15, nel rispetto anche dei diritti altrui','Sì, perché l’accesso non dà diritto a conoscere dati concreti','No, perché deve inviare automaticamente l’intero archivio senza valutazioni'],0,'Il diritto di accesso non si esaurisce in una descrizione astratta; va garantito in modo completo e comprensibile, tutelando nel contempo diritti e libertà di altri soggetti.','garante'],
['hdp4','Privacy','Un operatore invia per errore a un destinatario esterno un file contenente dati personali. Qual è la prima qualificazione corretta dell’evento?', ['Può costituire una violazione di dati personali da valutare e gestire secondo le procedure applicabili','È irrilevante se il file è stato inviato una sola volta','È automaticamente lecito perché l’invio non era intenzionale'],0,'La divulgazione non autorizzata può integrare una violazione di dati personali. L’evento va valutato e gestito secondo le responsabilità e procedure previste.','gdpr'],
['hdp5','Privacy','Quale scelta rispetta meglio il principio di limitazione della conservazione?', ['Stabilire tempi di conservazione per categorie di documenti e cancellare o anonimizzare dati non più necessari','Conservare tutto senza limiti perché in futuro potrebbe servire','Cancellare ogni dato subito dopo la raccolta, anche se esiste un obbligo di conservazione'],0,'Il principio richiede un tempo non superiore al necessario, valutato rispetto a finalità e obblighi applicabili: non conservazione indiscriminata né cancellazione automatica.','gdpr'],
['hdp6','Privacy','In un avviso alle famiglie, il servizio pubblica il numero complessivo dei partecipanti a un laboratorio senza indicare nomi o elementi identificativi. Perché questa situazione è diversa dalla diffusione di un elenco nominativo?', ['Un dato aggregato non consente, in quel contesto, di identificare direttamente le persone','Un numero complessivo è sempre un dato particolare','La pubblicazione di un elenco nominativo non riguarda mai dati personali'],0,'Il GDPR protegge informazioni riferite a persone identificate o identificabili. Un dato aggregato genuinamente non identificativo ha natura diversa da un elenco nominativo.','gdpr'],
['hdt1','TUEL e PA','Il Consiglio comunale approva un atto di indirizzo. In seguito, la Giunta adotta un provvedimento coerente con quell’indirizzo, non riservato al Consiglio. Quale lettura è corretta?', ['La sequenza è coerente: il Consiglio indirizza e la Giunta collabora nell’attuazione degli indirizzi generali','La Giunta non può mai adottare atti dopo un indirizzo del Consiglio','Il Consiglio deve svolgere direttamente ogni atto di gestione'],0,'Il TUEL distingue indirizzo e controllo del Consiglio dalle funzioni della Giunta, che collabora nell’attuazione degli indirizzi generali del Consiglio.','tuel'],
['hdt2','TUEL e PA','Quale affermazione è corretta sul regolamento relativo all’ordinamento di uffici e servizi?', ['È adottato dalla Giunta nel rispetto dei criteri generali stabiliti dal Consiglio','È adottato solo dal Consiglio senza alcun ruolo della Giunta','È sempre adottato dal Sindaco con ordinanza'],0,'L’art. 48 TUEL attribuisce alla Giunta l’adozione del regolamento, nel rispetto dei criteri generali fissati dal Consiglio.','tuel'],
['hdt3','TUEL e PA','Un dipendente deve decidere su una pratica che riguarda una società di cui un familiare stretto è amministratore. Quale comportamento è conforme al Codice?', ['Segnalare la situazione e astenersi secondo le regole applicabili','Trattare la pratica più rapidamente per dimostrare imparzialità','Proseguire senza comunicare nulla se ritiene di essere obiettivo'],0,'Il Codice richiede di agire con indipendenza e imparzialità e di astenersi in caso di conflitto di interessi, anche potenziale secondo le regole applicabili.','dpr62'],
['hdt4','TUEL e PA','Un cittadino insiste per ricevere un trattamento privilegiato perché conosce personalmente un dipendente. Quale risposta rispetta il Codice di comportamento?', ['Applicare le regole e assicurare parità di trattamento a parità di condizioni','Accogliere la richiesta per evitare tensioni','Rifiutare ogni richiesta del cittadino senza spiegazioni'],0,'Il dipendente deve evitare favoritismi e azioni arbitrarie, assicurando parità di trattamento a parità di condizioni.','dpr62'],
['hdt5','TUEL e PA','Perché il divieto di usare informazioni d’ufficio a fini privati è collegato all’imparzialità?', ['Perché impedisce che informazioni ottenute grazie al ruolo siano sfruttate per vantaggi personali o di terzi','Perché vieta ogni comunicazione tra pubbliche amministrazioni','Perché obbliga a rendere pubblici tutti i documenti'],0,'L’uso privato di informazioni d’ufficio può generare vantaggi indebiti e compromettere imparzialità e fiducia nell’amministrazione.','dpr62'],
['hde1','Inglese B2','Choose the correct option: “If the report ____ on time, the committee would have examined it yesterday.”', ['had been submitted','was submitted','would be submitted'],0,'This is a third conditional referring to an unreal past condition: if + past perfect passive, would have + past participle.'],
['hde2','Inglese B2','Choose the correct option: “The educator asked whether the parents ____ the consent form.”', ['had signed','have signed','will sign'],0,'In reported speech, a present perfect action is commonly backshifted to past perfect when the reporting verb is in the past.'],
['hde3','Inglese B2','Choose the correct option: “Hardly ____ the activity begun when one child asked to leave.”', ['had','did','was'],0,'Formal inversion after hardly: Hardly had + subject + past participle … when …'],
['hde4','Inglese B2','Choose the correct option: “The team agreed ____ the plan after reviewing the observations.”', ['to revise','revising to','revise that'],0,'Agree is followed by the infinitive: agree to revise.'],
['hde5','Inglese B2','Choose the correct option: “The more carefully the educator observes, the ____ the project becomes.”', ['more responsive','most responsive','responsive'],0,'The correlative comparative structure is: the more…, the more….'],
['hde6','Inglese B2','Choose the correct option: “It is essential that every record ____ stored securely.”', ['be','is','was'],0,'In formal English, after “It is essential that…”, the subjunctive base form may be used: be stored.'],
['hdi1','Informatica','Una pagina di accesso imita il sito di un servizio noto, ma l’indirizzo web contiene una lieve differenza nel dominio. Qual è il comportamento più corretto?', ['Non usare il link ricevuto: raggiungere il servizio dall’indirizzo ufficiale conosciuto o dall’app ufficiale','Inserire le credenziali perché il design della pagina è identico','Condividere il link in una chat per chiedere ad altri di inserire le proprie credenziali'],0,'Il phishing può imitare grafica e testi. Un dominio anomalo è un segnale di rischio: è più sicuro raggiungere il servizio da un canale ufficiale indipendente.','agid'],
['hdi2','Informatica','Perché l’autenticazione a due fattori migliora la sicurezza rispetto alla sola password?', ['Perché richiede un secondo elemento di verifica, riducendo il rischio se la password viene compromessa','Perché rende inutile avere una password','Perché permette di condividere le credenziali senza rischi'],0,'Un secondo fattore, come OTP o app, aggiunge una verifica separata dalla password e riduce il rischio di accessi non autorizzati.','agid'],
['hdi3','Informatica','Un file allegato a un’email proviene da un mittente apparentemente noto ma presenta un nome insolito. Qual è la procedura più prudente?', ['Verificare con un canale indipendente prima di aprirlo e seguire le procedure del servizio','Aprirlo subito perché il mittente è noto','Disabilitare le protezioni del dispositivo per visualizzarlo'],0,'Anche account conosciuti possono essere compromessi. La verifica indipendente riduce il rischio di malware o phishing.','agid']
].forEach(x=>add(x[0],x[1],'difficile',x[2],x[3],x[4],x[5],x[6]));

/* Distribuzione controllata delle risposte. Ogni quiz conserva le stesse tre
   alternative, ma l'ordine cambia in modo stabile in base all'identificativo:
   le risposte corrette risultano distribuite tra A, B e C. */
window.QUESTIONS.forEach(q=>{
  const shift=[...q.id].reduce((sum,ch)=>sum+ch.charCodeAt(0),0)%3;
  const order=[0,1,2].map(i=>(i+shift)%3);
  const original=q.options;
  q.options=order.map(i=>original[i]);
  q.answer=order.indexOf(q.answer);
});
